#! /bin/sh
#                  ██ ██ ███    ██ ████████ ███████ ██   ██ ██   ██ ██ 
#                  ██ ██ ████   ██    ██    ██      ██  ██  ██  ██  ██ 
# █████ █████      ██ ██ ██ ██  ██    ██    █████   █████   █████   ██ 
#             ██   ██ ██ ██  ██ ██    ██    ██      ██  ██  ██  ██  ██ 
#              █████  ██ ██   ████    ██    ███████ ██   ██ ██   ██ ██

### AUTOSTART ###
monitors.sh &
sxhkd &
alacritty &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-3 -d 1
bspc monitor DisplayPort-1-5 -d 2
bspc monitor HDMI-A-1-3 -d 3

bspc config border_width         1
bspc config window_gap          12

bspc config normal_border_color \#ADDA78
bspc config active_border_color \#ADDA78
bspc config focused_border_color \#F38D70

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme     spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
